In [107]:
import pandas as pd
from pandas import Series, DataFrame

In [57]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [58]:
obj.values

array([ 4,  7, -5,  3])

In [59]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [60]:
# Index可以不一定是要從0開始也可以是其他的內容，我們可以這樣宣告：
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [61]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [62]:
obj2.values

array([ 4,  7, -5,  3])

In [63]:
obj2['a']

-5

In [64]:
'a' in obj2.index

True

In [65]:
obj2['d'] = 6

In [66]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [67]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [68]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [69]:
# 你也可以搭配numpy一起用喔！
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [71]:
# 你也可以將dict的格式引入給pandas喔！＠
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [72]:
# 更改內容
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [73]:
# 內容是否為空值
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [74]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [75]:
# NaN因為index不同了
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [76]:
# 你還可以設定名稱喔！
obj4.name = 'population'
obj4.index.name = 'state'
obj4.index.name

'state'

In [77]:
obj4.name 

'population'

In [78]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [3]:
import pandas as pd

In [4]:
## Dataframe
'''

A DataFrame represents a rectangular table of data and contains an ordered collection of columns,
each of which can be a different value type (numeric, string, boolean, etc.).

While a DataFrame is physically two-dimensional, you can use it to represent higher dimensional 
data in a tabular format using hierarchical indexing. Will be taught when ch8.
'''


data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
            'year': [2000, 2001, 2002, 2001, 2002, 2003],
            'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [22]:
frame.head()     # 顯示前五筆資料

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [79]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) #指定column名稱的順序

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [6]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],index=['one', 'two', 'three', 'four','five', 'six'])
frame2  #對應不到的值顯示NaN

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [7]:
# 只能用在行索引
frame2['state'] #取得DataFrame的某一column -> 回傳一個Series
# frame2['two'] #→錯誤

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [110]:
# python提供較方便的方式
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [8]:
# 可以用loc來找到column上的data 可以搜尋列
frame2.loc['two']

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [9]:
frame2.iloc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [93]:
# 新增debt的資料
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [94]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [95]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val #把一Series新增給DataFrame
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [98]:
# 巢狀dict做pd
# 外層字典的key作為column欄位名稱, 內層字典的key為row欄位名稱
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [99]:
# 可以用Ｔ來將row & col翻轉
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [100]:
# 為index, columns取名
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [101]:
# 跟Series一樣，value屬性會以二維陣列形式回傳DataFrame資料
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [104]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [106]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [102]:
frame3.values.dtype

dtype('float64')

In [103]:
# 若DataFrame裡column資料類型不同，則系統會選最適用於能兼容所有column的資料類型
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [38]:
'''

Table 5-1. Possible data inputs to DataFrame constructor

'''

'\n\nTable 5-1. Possible data inputs to DataFrame constructor\n\n'

In [32]:
## Index Objects
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [40]:
index[1:]

Index(['b', 'c'], dtype='object')

In [53]:
index[1] = 'd'
# index objects是不能改變的，所以會出現Type error.

# obj.index = ['a', 'd', 'c']
# obj.index
# Index Objects的不可修改性很重要，才能讓Index在多個資料結構中安全共享

Index(['a', 'd', 'c'], dtype='object')

In [ ]:
labels = pd.Index(np.arange(3)) # 透過重新指向新陣列方式，更改index值
labels

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels) # 透過重新指向新陣列方式，更改index值
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
'''

與一般的python set不一樣，pandas可以有相同的index出現在同一個dataframe.

'''
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [ ]:
'''

Other methods.
Table 5-2. Some Index methods and properties

'''