## **課前QA**

#### 1.GCD邏輯

In [ ]:
def gcd(a,b): 
    a, b = (a, b) if a >=b else (b, a)
    if a%b==0: 
        return b 
    else: 
        return gcd(b,a%b) 
  
  
# prints 12 
print ("The gcd of a and b is : ",end="") 
print (gcd(22,121)) 

In [ ]:
def ggcd(x,y):
    if x>y:
        k = [i for i in range(1,y+1) if (x%i)==0 & (y%i)==0]
    else:
        k = [i for i in range(1,x+1) if ()]

#### GCD邏輯

In [55]:
text = 'I like python because python has full plugins. And Using plugins can save our much time.'
dict_text = {} #建一個空dict
for word in text.split():
    if word not in dict_text:
        dict_text[word] = 1
    else:
        dict_text[word] += 1
dict_text

{'I': 1,
 'like': 1,
 'python': 2,
 'because': 1,
 'has': 1,
 'full': 1,
 'plugins.': 1,
 'And': 1,
 'Using': 1,
 'plugins': 1,
 'can': 1,
 'save': 1,
 'our': 1,
 'much': 1,
 'time.': 1}

##### 2.詞頻邏輯

# **1206 資料前處理**
https://hackmd.io/-fvqakZkSECVVVwY5fo-dA?view

##### **練習 用list做矩陣乘法**

In [35]:
import numpy as np 
list1 = [0,1,2,3,4,5,6,7,8,9]
#print(np.array(list1)*2)
list_a = np.array(list1)
list_a
print(list_a*2)

[ 0  2  4  6  8 10 12 14 16 18]


In [60]:
list1 = [0,1,2,3,4,5,6,7,8,9]
lift2 = [i * 2 for i in list1]
lift2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [36]:
list1 = [0,1,2,3,4,5,6,7,8,9]
for i in list1:
    list1[i] = list1[i]*2
print(list1)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


##### 預設格式 : float64

### **ndarray**

In [2]:
import numpy as np
a = [1,2,3]
b = [[1,2,3],[4,5,6]]
c = np.array(a)
d = np.array(b)
print(a)
print(b)
print(c)
print(d)
print(c*d)

[1, 2, 3]
[[1, 2, 3], [4, 5, 6]]
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [ 4 10 18]]


In [3]:
data2 =[[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
arr2.shape

(2, 4)

In [5]:
arr2.dtype

dtype('int32')

In [6]:
arr2.ndim

2

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
np.empty((4,8,2)) #2個3*2矩陣

array([[[ 4.67296746e-307,  1.69121096e-306],
        [ 9.34609111e-307,  1.33508845e-306],
        [ 1.33511969e-306,  6.23037996e-307],
        [ 1.06811422e-306,  9.34562257e-307],
        [ 6.44890786e+265,  3.94646009e+180],
        [ 1.69600558e+161,  6.01346953e-154],
        [ 4.67661267e+252,  2.52301823e-258],
        [ 6.96742065e+252,  1.65524320e-153]],

       [[ 7.26584463e+223,  1.85019220e-070],
        [ 1.51327986e+256,  7.36178176e+223],
        [ 6.96771781e+252,  2.23674567e-046],
        [ 6.47434877e-067,  1.48970349e+214],
        [ 1.48972616e+214,  1.48972206e+214],
        [ 1.48972413e+214,  1.48972620e+214],
        [ 8.61480111e+183,  1.80546597e-259],
        [ 3.65588280e+233,  3.62464572e+228]],

       [[ 1.50753760e-153,  2.20924030e-070],
        [ 2.21211602e+214,  3.62464579e+228],
        [ 1.45036783e-047,  9.05437256e+271],
        [ 6.01346953e-154,  3.81391472e+180],
        [ 4.23971605e+175,  2.66293521e-260],
        [ 1.27778246e+161,  3.

In [10]:
arr = np.arange(9).reshape((3,3))
arr_1 = arr[:2,1:]
arr_1.shape
arr_2 = arr[2]
arr_2.shape
arr_3 = arr[2:,:]
arr_3.shape

(1, 3)

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##### **隋堂練習1**

In [11]:
arr = np.arange(45).reshape((3,5,3))
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]]


In [15]:
arr[:2,:3,1:]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[16, 17],
        [19, 20],
        [22, 23]]])

##### **隨堂練習2**

In [16]:
names = np.array(['Alice','Lucy','Bob','Lucy'])
names == 'Lucy'

array([False,  True, False,  True])

In [23]:
name_array = np.array(['Alice', 'Lucy', 'Bob', 'Lucy'])
info_array = np.array([[158, 55], [165, 60], [185, 70],[155,45]])
info_array[name_array == 'Lucy']

array([[165,  60],
       [155,  45]])

In [24]:
name_array = np.array(['Alice', 'Lucy', 'Bob', 'Lucy'])
info_array = np.array([[158,165,185,155], [55,50,70,45]])
info_array[:2,name_array == 'Lucy']

array([[165, 155],
       [ 50,  45]])

##### **隨堂練習3**

In [17]:
salary = np.array([30000,80000,40000,45000])
salary

array([30000, 80000, 40000, 45000])

In [19]:
a = salary[(salary >= 30000) & (salary <= 80000)]
(a-30000)/50000

array([0. , 1. , 0.2, 0.3])

In [21]:
money = np.array([30000,80000,40000,45000])
print(money)
print('---')
amin, amax = np.min(money), np.max(money)
result = (money - amin)/(amax - amin)
print(result)

[30000 80000 40000 45000]
---
[0.  1.  0.2 0.3]


##### **隨堂練習4 - 4.6** 

In [25]:
np.random.seed([50])
array_1 = np.random.rand(4)
np.random.seed([48])
array_2 = np.random.rand(4)
array_1
array_2

array([0.54815783, 0.13189146, 0.71154684, 0.30225006])

In [26]:
array_x = array_1 * array_2
array_x

array([0.27272857, 0.03510604, 0.4535479 , 0.07328952])

In [130]:
array_x.sum()

0.8346720253493024

In [135]:
array_x.mean()

0.2086680063373256

In [27]:
rng = np.random.RandomState(50)
rng1 = np.random.RandomState(48)
array1 = rng.randn(2,2)
array2 = rng1.randn(2,2)

result = np.multiply(array1, array2)
result.sum()
result.mean()

0.10619343231884187