In [2]:
import numpy as np

In [102]:
## Creating ndarrays
'''
將一個array用numpy的函式展現出來的話，numpy會提供一個新的numpy array來
裝載他，並以浮點數的方式存放。
'''
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [103]:
# Shapes & Types of Array
'''
一個多維度矩陣(ndarray)會給予相同性質的data一個多維的容器，也就是說，所有的
元素必須要是相同屬性(type)的。
因此每個array都會擁有一個「Shape」，用tuple的方式來表示這個矩陣的維度，也會
有一個「dtype」去描述這個矩陣的屬性。

'''
arr1.shape #數值

(5,)

In [21]:
arr1.dtype #型態

dtype('float64')

In [112]:
# Nested sequences
'''
如果處理的多個相同長度的list，會被轉換成多維度的矩陣。
'''
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr_2 = np.array(data2)
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [113]:
arr_2.shape

(2, 4)

In [105]:
arr2.dtype # int np array會找出最適合data的資料型態

dtype('float64')

In [ ]:
# 輸出arr2有多少維度
arr2.ndim

In [5]:
# 其他創新矩陣的方法
'''
在np.array當中你有很多種不同的方式可以做出新矩陣，例如說重複使用零與一的方式來製作一個矩陣。
你只要輸入參數到裡面np就會自動幫你輸出等量的零來製作一個矩陣。
np.array, there are a number of other functions for creating new arrays.
As examples, zeros and ones create arrays of 0s or 1s, respectively, with a given length or shape.

'''
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [7]:
np.ones((3, 5), dtype = 'float32')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [108]:
'''
empty可以拿來製作未經初始化的陣列。
PS. It’s not safe to assume that np.empty will return an array of all zeros.
In some cases, it may return uninitialized “garbage” values.
如下：書上所產生的都是零，但是實際上跑出來的卻是拉機數據。

＊np.empty創造二十四個元素均為未初始化的值
'''
a = np.empty((2,3,2))     #兩個3*2的矩陣合在一起的感覺\
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [107]:
a.shape

(2, 3, 2)

In [10]:
np.arange(15, 32, 2)

array([15, 17, 19, 21, 23, 25, 27, 29, 31])

In [12]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [7]:
'''
因為numpy較注重於"numbrical computing"，因此他所使用的函數常常會吐出float形態的輸出。
如(圖4-1)
'''
## Data types for ndarrays
# dtype 為 ndarry 的物件屬性
# 指定ndarry之陣列資料型態屬性
arr1 = np.array([1, 2, 3], dtype=np.float64) # np.array : Convert input data
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

In [11]:
ar = np.array([1,2,3,4,5,6,7])
ar.dtype

dtype('int32')

In [14]:
'''
numpy當中有很多不同的data types，如(圖4-2)，假如你是新手的話其實也不用那麼在意資料型態，
除非你今天有必要處理大量的資料，那麼對於容量大小的控制你可能就要謹慎的選擇你的data type.
'''

# 陣列屬性為'int64'
arr = np.array([1, 2, 3, 4, 5], dtype=np.int64)
arr.dtype

dtype('int64')

In [15]:
# 顯式轉換其dtype -> astype
# 經過'astype'的轉換變成'float64'了
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [16]:
# 那如果我把原本是float的陣列轉換成int呢？
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.dtype

dtype('float64')

In [17]:
# 他就會把尾數給去掉喔！真是聰明呢！
arr.astype(np.int64) # 如果使用astype就一定會新增出一個新的array，就算舊的dtype跟新的完全一樣也是。

array([ 3, -1, -2,  0, 12, 10], dtype=int64)

In [18]:
# Using "Type code"
empty_uint32 = np.empty(8, dtype='u4') # 也可用簡潔類型程式碼來表示dtype，八個並且type為uint32
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [110]:
## Arithmetic with NumPy Arrays
'''
矩陣的重要性在於他們可以讓你不需要使用迴圈就可以操作了。NumPy使用者把這種特性稱為「vectorization」。
相同大小的矩陣就可以直接依內部的元素直接進行操作。
'''
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [21]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
1 - arr

array([[ 0., -1., -2.],
       [-3., -4., -5.]])

In [23]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
# 也可以拿他們來做布林運算喔！
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

In [25]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

In [116]:
## Basic Indexing and Slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
arr[5]    #把第五個數字叫出來

5

In [118]:
arr[5:8]  #把大於等於五小於八的數字叫出來

array([5, 6, 7])

In [119]:
arr[5:8] = 12  # 更改內容成為12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [120]:
# 這個時候數值是已經被更改的狀態了，所以假設你再從中將其提出來的話
get_array = arr[5:8]
get_array
# 都變成12囉喔喔喔喔喔

array([12, 12, 12])

In [121]:
arr
# 沒有錯，他與先前所製作的array是連動的，一個指標的概念，是不是很棒呢？

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [58]:
# 完全沒有範圍的矩陣(bare-slice)會等同全部都更改了
get_array[:] = 9527
get_array

array([9527, 9527, 9527])

In [122]:
list1 = list(range(5))
list1[1:2] = (2,2)
list2 = list1[1:2]
list2[0] = 5
list2

[5]

In [59]:
'''
大部分的語言都跟這種傳值方式不太一樣，大多是採用copy的方式去做更換會比較多，
但是在numpy裡面，他被設計成能夠去處理「大型矩陣」，因此假如使用大量copy的方
式，可想而知他的效能會變得多低了。

那假如不想要連動，可以使用"copy()"
'''
arr[5:8].copy()

array([9527, 9527, 9527])

In [88]:
# 越高維度的array你擁有的選項就越多，像是在2維矩陣中，你如果只找出其中一個值，
# 他不會吐出單一數值，而是會給你一個一維矩陣。
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
# 因此你如果想要找出其中一個值，你可以用重複尋找的方式去找，但這樣太憨了，
# 你可以改用下列這兩種方式來做
arr2d[0][2]
# arr2d[1][0]

4

In [62]:
arr2d[0,2]

3

In [18]:
'''
如果你不知道該怎麼分row跟column的話，就看個圖吧
 ___________
|rows  ->   |c  |
|           |o  V
|           |l
|           |u
|           |m
|___________|n

在python裡面的矩陣nXm （n先向下看，m再向右看）[**先看幾Rows(列)，在看幾Column（行）**]
'''
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d
#arr3d.shape

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [127]:
arr3d[0]  # 三維的第一個，就是二維的所以輸出二維陣列

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# 不管是單ㄧ值或是矩陣都可以被寫入arr3d[0]
old_values = arr3d[0].copy()
arr3d[0] = 42 # 單一值
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
old_values   # 矩陣
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [94]:
arr3d[1,:2] # 先找1在找0

array([[ 7,  8,  9],
       [10, 11, 12]])

In [70]:
## Indexing with slices
arr

array([   0,    1,    2,    3,    4, 9527, 9527, 9527,    8,    9])

In [71]:
# 跟一維矩陣一樣，也可以用ndarray作相似的切割
arr[1:6]

array([   1,    2,    3,    4, 9527])

In [131]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d      # 拿之前的arr2d來當例子的話

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[:2]   # 0, 1 從最前面一直到小於2的地方
            # 書上說就如同”select the first two rows of arr2d“

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# 你也可以用這種方式來取得想要的矩陣
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2d[1, :2]

array([4, 5])

In [77]:
arr2d[:2, 2]

array([3, 6])

In [ ]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [129]:
arr2d[:2, 1:] = 1
arr2d

array([[1, 1, 1],
       [4, 1, 1],
       [7, 8, 9]])

In [80]:
## Boolean Indexing 布林型索引

# 在這裡我們用一個np.array來存放一些有重複的名字，並且做出一個7X4的隨機矩陣。

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4) #使用numpy.random中的randn函數生成常態分佈的隨機資料
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [81]:
data

array([[ 1.72764924,  0.63698236,  0.28644786,  0.54468223],
       [ 0.03449321,  0.21510787,  0.01065171,  0.32555218],
       [ 0.91959993,  0.04275693, -0.47841508, -0.16011462],
       [-0.76906844,  1.09604459, -0.48872472, -1.20913929],
       [-0.93163443,  0.83339235, -0.06041109,  0.7722885 ],
       [-2.33089945, -0.29624945, -0.22738234,  0.35329254],
       [-0.52597578,  0.38387173,  0.37593967, -1.04738471]])

In [82]:
# 可以利用布林運算來找出哪裡含有"Bob", 對names和Bob的比較運算會產生布林型陣列
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [83]:
# 此布林型陣列可直接作為索引值。
data[names == "Bob"]   # => data[0] && data[3]

array([[ 1.72764924,  0.63698236,  0.28644786,  0.54468223],
       [-0.76906844,  1.09604459, -0.48872472, -1.20913929]])

In [ ]:
'''
布林矩陣必須要與array相同大小，你甚至可以將布林矩陣與其他整數或slices混合使用。
必須要注意的是，如果你的大小設定為不同的話，系統並不會提出警告，因此要小心使用。

'''

In [132]:
# arange(32)可以製作0~32的數字，然後再用「reshape」來將它轉換為8X4的矩陣
arr = np.arange(32).reshape((8, 4))
#arr = np.arange(32).reshape((2,4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [133]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]   # 先看arr[[1,5,7,2]](向下找)，再去看arr[[0,3,1,2]](向右找)
                                  # elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected.
                                  # 出來

array([ 4, 23, 29, 10])

In [134]:
## Transposing Arrays and Swapping Axes 陣列轉置與軸轉換
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [135]:
# 轉喔～橫的變直的
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [136]:
arr = np.random.randn(6, 3)
arr

array([[ 0.78027761, -0.99072222,  0.70131617],
       [ 0.50603163, -0.71245654, -0.09099757],
       [-2.23374073,  1.27498754,  1.54151762],
       [-0.24947885,  2.22980422,  1.12861036],
       [-1.43860695,  0.15512128,  0.41983421],
       [ 0.064748  , -0.60812129,  1.01589745]])

In [137]:
np.dot(arr.T, arr)     # 矩陣內積x(T) * x

array([[ 7.99052078, -4.80037769, -3.76194053],
       [-4.80037769,  8.48061902,  3.29935454],
       [-3.76194053,  3.29935454,  5.35847123]])

In [24]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
# 一般的矩陣用Ｔ，ndarray就用swapaxes()的函式。
b = arr.swapaxes(0, 2)   # 第0個與第2個位子相交換
b

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [23]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [2, 6])
print(x1, x2, x3)

[1 2] [ 3 99 99  3] [2 1]


In [13]:
b.shape       # 原本是(2,2,4)變成(4,2,2)

(4, 2, 2)