In [1]:
### 4-2 Universal Functions: Fast Element-Wise Array Functions
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
## Maths
# unary func -> sqrt, exp, modf
# np.sqrt(arr) #開根號
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
# np.exp(arr) #返回e的n次方，e是一个常數為2.71828
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [4]:
arr = np.random.randn(7) * 5
arr

array([-2.49524494,  1.38911553, -0.87046352,  3.67382198,  6.38771296,
        1.3517446 , -1.98722782])

In [5]:
remainder, whole_part = np.modf(arr)      # modf會幫你把數字轉變成整數部分與小數點部分
remainder

array([-0.49524494,  0.38911553, -0.87046352,  0.67382198,  0.38771296,
        0.3517446 , -0.98722782])

In [14]:
whole_part

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
np.modf(arr)                          # 稍微看看modf裡面有什麼，有兩個矩陣分別存取整數與小數點

(array([-0.98430103,  0.58132865,  0.18258665,  0.87752484,  0.62639507,
         0.99325398, -0.72755899]), array([-1.,  2.,  3.,  4.,  2.,  1., -3.]))

In [20]:
# binary func -> np.maximux
x = np.random.randn(8)
y = np.random.randn(8)

In [24]:
x

array([-0.76098459, -1.01368829, -0.40635129, -1.51243046, -0.23080189,
       -0.24853383, -0.81687265, -0.44637063])

In [22]:
y

array([-0.08974612,  2.23949648,  0.24407044,  0.60777515,  0.41072912,
       -1.37425949, -0.05877626, -2.23682857])

In [23]:
# np裡面有最大值的函數
np.maximum(x,y)

array([-0.08974612,  2.23949648,  0.24407044,  0.60777515,  0.41072912,
       -0.24853383, -0.05877626, -0.44637063])

In [11]:
np.add(x, y)

array([-0.40417541,  0.90437878, -1.38329905, -0.54896246, -1.28706792,
        0.82530713, -0.44861491, -0.1493992 ])

In [12]:
'''
其他unary & binary func 可以到教材上看看

'''

'\n其他unary & binary func 可以到教材上看看\n\n'

In [6]:
np.arange(5)/np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [12]:
x = np.arange(4)
print('x + 2 =', x+2)
print('x + 3 =', np.add(x,3))

x + 2 = [2 3 4 5]
x + 3 = [3 4 5 6]


In [21]:
# x = np.arange(5)
a = np.empty(5)
# np.multiply(x, 10, out = y)
print(a)

[ 0. 10. 20. 30. 40.]
