In [ ]:
import numpy as np
arr = np.arange(10)

# 利用這個方法就可以將你的np儲存為".npy"檔案
np.save('some_array', arr)

In [ ]:
# 這個方法可以拿來載入.npy file
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# savez 可以拿來儲存多個陣列，儲存為.npz file
a = [1,2,3,4,5,6,7]
b = [8,9,1,2,3,4,5]
np.savez('array_archieve.npz', x=a, y=b)

In [ ]:
arch = np.load('array_archieve.npz')
arch['x']

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arch['y']

array([8, 9, 1, 2, 3, 4, 5])