In [4]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [5]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [6]:
x.dot(y)      # 相乘

array([[  28.,   64.],
       [  67.,  181.]])

In [7]:
np.dot(x, np.ones(3))    # 與下方的是一樣的

array([  6.,  15.])

In [8]:
x @ np.ones(3)

array([  6.,  15.])

In [27]:
# 線性代數耶！哇耶逼！自己看
from numpy.linalg import inv, qr

X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 1.42881402,  0.51148297, -0.21155535, -0.91662981, -0.47618681],
       [ 0.51148297,  0.61116314, -0.15260906, -0.39806062, -0.55793334],
       [-0.21155535, -0.15260906,  0.42813367,  0.39843437, -0.12063054],
       [-0.91662981, -0.39806062,  0.39843437,  1.10246483,  0.02939924],
       [-0.47618681, -0.55793334, -0.12063054,  0.02939924,  1.11351972]])

In [28]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   1.41357942e-16,   3.67773824e-17,
          1.19507202e-16,  -2.22044605e-16],
       [  4.88007599e-16,   1.00000000e+00,   6.03148058e-17,
          4.96933455e-16,   0.00000000e+00],
       [ -2.95220662e-16,  -7.19683957e-17,   1.00000000e+00,
          1.72135139e-16,   2.22044605e-16],
       [  2.96135153e-16,   1.61695667e-16,  -1.27772884e-16,
          1.00000000e+00,   0.00000000e+00],
       [  2.22044605e-16,  -2.22044605e-16,   5.55111512e-17,
          2.91433544e-16,   1.00000000e+00]])

In [29]:
q, r = qr(mat)
r

array([[-3.16276332, -2.49395962,  1.37695006, -4.54177528, -2.60615949],
       [ 0.        , -6.33289384, -2.95122415, -1.12731101, -3.79051367],
       [ 0.        ,  0.        , -3.57299938,  1.4442429 , -0.5209545 ],
       [ 0.        ,  0.        ,  0.        , -0.68694097,  0.25880698],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.74672922]])