In [1]:
import numpy as np

In [ ]:
# 用這方法來做隨機常態分配矩陣
samples = np.random.normal(size=(4, 4))
samples

array([[-0.69373163,  0.63480924,  0.51312454, -0.24276286],
       [ 0.01353425, -1.3960528 , -1.53696376, -0.5352837 ],
       [-1.06704351, -0.56479132, -0.45200991,  1.86296131],
       [-0.86062909, -0.1385359 ,  0.91948897, -0.14092495]])

In [ ]:
from random import normalvariate
N = 1000000

# 這邊就是在說numpy好棒棒他比較快。
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)


800 ms ± 32.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
30.6 ms ± 987 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
#seed 固定隨機的起始點，讓每次隨機產生的結果一樣
# You can change NumPy’s random number generation seed using np.random.seed
np.random.seed(1234)

# The data generation functions in numpy.random use a global random seed. To avoid global state,
# you can use numpy.random.RandomState to create a random number generator isolated from others
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [ ]:
'''

Table 4-8. Partial list of numpy.random functions

'''

In [15]:
rng = np.random.RandomState(50)
rng1 = np.random.RandomState(48)
rng.randn(2,2,3)

array([[[-1.56035211, -0.0309776 , -0.62092842],
        [-1.46458049,  1.41194612, -0.47673214]],

       [[-0.78046921,  1.07026774, -1.2822926 ],
        [-1.3274789 ,  0.12633764,  0.86219372]]])

In [16]:
rng1.randn(2,2,3)

array([[[-0.99363132, -1.06340081, -0.63807592],
        [ 1.06158869, -0.15740415,  1.09372848]],

       [[-2.07485402,  0.70063301,  1.67463863],
        [-0.39733411,  2.32379695, -0.99970063]]])

In [17]:
result = rng.randn(2,2,3)*rng1.randn(2,2,3)

In [21]:
result.sum()

7.2252583709789793